###################
# Global Settings #
###################

stages:
  - prepare
  - build_n_test

default:
  interruptible: true

variables:
  ENABLED_CLUSTERS: "darwin"
  GIT_SUBMODULE_STRATEGY: normal

.ascgit_job:
  id_tokens:
    SITE_ID_TOKEN:
      aud: https://asc-git.lanl.gov

.darwin_job:
  rules:
    - if: $ENABLED_CLUSTERS =~ /darwin/
  variables:
    CLUSTER: darwin
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p general,skylake-gold,skylake-platinum --constraint=\"(cpu_family:skylake)&ib:edr\""
  tags:
    - darwin-slurm-shared

.rocinante_job:
  variables:
    CLUSTER: rocinante
    SCHEDULER_PARAMETERS: "-N 1 -A asc-ci -p ci --reservation ci --time=00:45:00"
  tags:
    - rocinante
    - batch


.build_and_test:
  stage: build_n_test
  script:
    - source .gitlab/build_and_test.sh ${CLUSTER} ${SPACK_ENV_NAME}
  artifacts:
    expire_in: 2 weeks
    paths:
      - ${CI_PROJECT_DIR}/build/tests.xml
    reports:
      junit: ${CI_PROJECT_DIR}/build/tests.xml


########
# Jobs #
########

download_prereq:
  stage: prepare
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
   - .gitlab/download_prereq.sh
  artifacts:
    paths:
      - goldfiles.tar.gz

openmpi_gcc:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-gcc

openmpi_fortran_gcc:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-fortran-gcc

openmpi_cuda_gcc_ampere:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-cuda-gcc-ampere
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-ampere"

openmpi_cuda_gcc_volta:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-cuda-gcc-volta
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell"

openmpi_fortran_kokkos_openmp_gcc:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-fortran-kokkos-openmp-gcc

openmpi_fortran_kokkos_static_openmp_gcc:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-fortran-kokkos-static-openmp-gcc

openmpi_rocm_gcc:
  extends: [.ascgit_job, .darwin_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: openmpi-rocm-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-amd-mi250"

craympich_gcc:
  extends: [.ascgit_job, .rocinante_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: craympich-gcc

craympich_fortran_gcc:
  extends: [.ascgit_job, .rocinante_job, .build_and_test]
  needs: [download_prereq]
  variables:
    SPACK_ENV_NAME: craympich-fortran-gcc
