name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    tests:
      name: Run Unit and Regression Tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: sudo apt-get install -y --force-yes -qq build-essential gfortran libhdf5-serial-dev python-numpy python-h5py python3-numpy python3-h5py
        - name: build and run tests
          run: |
            mkdir -p bin
            cd bin
            mkdir -p ${HOME}/install
            cmake -DCMAKE_INSTALL_PREFIX=${HOME}/install -DSINGULARITY_BUILD_TESTS=ON -DSINGULARITY_USE_HDF5=ON -DSINGULARITY_TEST_SESAME=OFF -DSINGULARITY_TEST_STELLAR_COLLAPSE=ON ..
            make -j
            make install
            make test
